services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./.pypoetry:/root/.cache/pypoetry/
    command: sh -c "while true; do sleep 1; done"