# Generated by Django 5.2 on 2025-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uiuser',
            options={'verbose_name': 'UI user', 'verbose_name_plural': 'UI users'},
        ),
        migrations.AddField(
            model_name='uiuser',
            name='password',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
